import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DarkFeatureConfig, DarkFeatureProvider } from "@darkfeature/sdk-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const darkFeatureConfig: DarkFeatureConfig = {
  apiKey: process.env.NEXT_PUBLIC_DARKFEATURE_API_KEY || '',
  context: {
    userId: 'madhu@darkfeature.com',
    email: 'madhu@darkfeature.com',
    version: '1.5.0',
    org: 'darkfeature',
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DarkFeatureProvider config={darkFeatureConfig}>
          {children}
        </DarkFeatureProvider>
      </body>
    </html>
  );
}
